### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by ph1l**
* remove some more references to the old install script
* adds a note about reporting problems with the new setup script

### CODE REVIEW

**Comment by ph1l** [comment]
@rob42 , since the original PR for the new setup script removed the old one, we should probably remove references to it in other documentation.

**Comment by rob42** [comment]
I didnt notice it removed the old one. Yes lets go full Jessie.

**Comment by ph1l** [comment]
Sorry, I didn't mean to force you on that issue. I can pull the old code and docs out and submit another PR to restore them, if you prefer.

**Comment by rob42** [comment]
No its fine - I was looking at it last night thinking about how/when to go 'full Jessie', you just made the decision easy :-)

May 20 2016 3:47 PM, "Philip Freeman"  wrote:
	Sorry, I didn't mean to force you on that issue. I can pull the old code and docs out and submit another PR to restore them, if you prefer.

**Comment by ph1l** [comment]
Okay.. I'll keep a lookout for problems, but feel free to ping me..

**Pull request merged**
